import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/toolkit/provider";
import SubHeader from "@/components/SubHeader";
import Developement from "@/components/developement";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="relative">
            <div className="fixed top-0 left-0 right-0 z-50">
              <Header />
            </div>
            <div className="mt-16">
            <SubHeader />
            <Developement/>
            </div>
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
